services:
  peer_1:
    build: ../../
    command:
    - python
    - p2p.py
    - 127.0.0.1:5001
    - infra/topologia_tres_triangulos/1.txt
  peer_10:
    build: ../../
    command:
    - python
    - p2p.py
    - 127.0.0.1:5010
    - infra/topologia_tres_triangulos/10.txt
  peer_2:
    build: ../../
    command:
    - python
    - p2p.py
    - 127.0.0.1:5002
    - infra/topologia_tres_triangulos/2.txt
  peer_3:
    build: ../../
    command:
    - python
    - p2p.py
    - 127.0.0.1:5003
    - infra/topologia_tres_triangulos/3.txt
  peer_4:
    build: ../../
    command:
    - python
    - p2p.py
    - 127.0.0.1:5004
    - infra/topologia_tres_triangulos/4.txt
  peer_5:
    build: ../../
    command:
    - python
    - p2p.py
    - 127.0.0.1:5005
    - infra/topologia_tres_triangulos/5.txt
  peer_6:
    build: ../../
    command:
    - python
    - p2p.py
    - 127.0.0.1:5006
    - infra/topologia_tres_triangulos/6.txt
  peer_7:
    build: ../../
    command:
    - python
    - p2p.py
    - 127.0.0.1:5007
    - infra/topologia_tres_triangulos/7.txt
  peer_8:
    build: ../../
    command:
    - python
    - p2p.py
    - 127.0.0.1:5008
    - infra/topologia_tres_triangulos/8.txt
  peer_9:
    build: ../../
    command:
    - python
    - p2p.py
    - 127.0.0.1:5009
    - infra/topologia_tres_triangulos/9.txt
version: '3'
